name: Test (NPM)
on:
  push:
    branches-ignore: ['main']
jobs:
  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    with:
      matrix_commands: '["lint", "depcheck", "check"]'
  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    with:
      tests: '["test"]'
      docker_compose_file: ""
  check-version:
    uses: digicatapult/shared-workflows/.github/workflows/check-version.yml@main